#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys
from nimbusclientlib import Notifier


if __name__ == "__main__":
    try:
        size = len(sys.argv)
        if size == 4:
            username, password, address = sys.argv[1:]
            Notifier(username, password, address).notify_new_computer()
        elif size == 5:
            username, password, address, port = sys.argv[1:]
            Notifier(username, password, address, port).notify_new_computer()
        else:
            print "usage: username password address [port]"
            sys.exit(1)
        sys.exit(0)
    except Exception, error:
        print error
        sys.exit(1)
