#!/bin/sh -e



case $1 in
    configure)
	/usr/sbin/useradd nimbus||echo;
	if [ ! -e /var/log/nimbus ];
	then
		mkdir /var/log/nimbus;
	fi;

	echo "/opt/bacula/lib" > /etc/ld.so.conf.d/bacula.conf;
	/sbin/ldconfig;
	/usr/sbin/update-rc.d nimbusmanager defaults; 
	/usr/sbin/update-rc.d nimbus defaults; 
	/usr/sbin/update-rc.d nimbusclient defaults; 
	/etc/init.d/mysql start;
	/usr/bin/mysql -uroot -pn1mbus < /var/nimbus/create.sql 2> /dev/null || echo;
    chown -R nimbus:nimbus /etc/nimbus/;
    chown -R nimbus:nimbus /var/log/nimbus/;
    chown -R nimbus:nimbus /var/nimbus/;
    chown -R nimbus:nimbus /var/www/;
    chmod -R 0775 /var/log/nimbus/;
    chmod -R 0775 /var/nimbus/;
    chmod -R 0775 /etc/nimbus/;
    chmod u+s /var/www/nimbus;
    /usr/sbin/adduser nimbus plugdev;
    /usr/sbin/adduser nimbus bacula;
	/etc/init.d/nimbusmanager restart ;
	/etc/init.d/nimbusclient restart ;
    su - nimbus -c '/var/www/nimbus --create-database';
    /etc/init.d/bacula-ctl-dir restart;
    /etc/init.d/bacula-ctl-sd restart;
    /etc/init.d/bacula-ctl-fd restart;
    /etc/init.d/nimbus restart;
    /etc/init.d/nginx restart;;
esac

