#!/bin/sh -e



case $1 in
    configure)
	/usr/sbin/useradd nimbus||echo;
	if [ ! -e /var/log/nimbus ];
	then
		mkdir /var/log/nimbus;
	fi;

	if [ ! -e /var/nimbus/custom/config/bacula-sd.conf ];
	then
        echo mv /var/nimbus/custom/config/bacula-sd.conf.default /var/nimbus/custom/config/bacula-sd.conf;
		mv /var/nimbus/custom/config/bacula-sd.conf.default /var/nimbus/custom/config/bacula-sd.conf;
	fi;

	if [ ! -e /var/nimbus/custom/config/bacula-dir.conf ];
	then
        echo mv /var/nimbus/custom/config/bacula-dir.conf.default /var/nimbus/custom/config/bacula-dir.conf;
		mv /var/nimbus/custom/config/bacula-dir.conf.default /var/nimbus/custom/config/bacula-dir.conf;
	fi;

	if [ ! -e /var/nimbus/custom/config/bconsole.conf ];
	then
        echo mv /var/nimbus/custom/config/bconsole.conf.default /var/nimbus/custom/config/bconsole.conf;
		mv /var/nimbus/custom/config/bconsole.conf.default /var/nimbus/custom/config/bconsole.conf;
	fi;



	echo "/opt/bacula/lib" > /etc/ld.so.conf.d/bacula.conf;
	/sbin/ldconfig;
	/usr/sbin/update-rc.d nimbusmanager defaults; 
	/etc/init.d/mysql start;
	/usr/bin/mysql -uroot -pn1mbus < /var/nimbus/create.sql 2> /dev/null || echo;
    echo "www-data ALL=NOPASSWD: /usr/bin/truecrypt" >> /etc/sudoers;

    /var/www/nimbus.fcgi syncdb --noinput -v 0;
    chown -R www-data:www-data /etc/nimbus/;
    chown -R www-data:www-data /var/log/nimbus/;
    chown -R www-data:www-data /var/nimbus/;
    chown -R www-data:www-data /var/www/;
    chmod -R 0775 /var/log/nimbus/;
    chmod -R 0775 /var/nimbus/;
    chmod -R 0775 /etc/nimbus/;
    /etc/init.d/bacula-ctl-dir restart;
    /etc/init.d/bacula-ctl-sd restart;
    /usr/sbin/a2enmod rewrite;
    killall -9 nimbus.fcgi;
    /etc/init.d/apache2 restart;
	/etc/init.d/nimbusmanager restart ;;
esac

