#!/bin/sh -e



case $1 in
    configure)
	/usr/sbin/useradd nimbus||echo;
	if [ ! -e /var/log/nimbus ];
	then
		mkdir /var/log/nimbus;
	fi;

	echo "/opt/bacula/lib" > /etc/ld.so.conf.d/bacula.conf;
	/sbin/ldconfig;
	/usr/sbin/update-rc.d nimbusmanager defaults; 
	/usr/sbin/update-rc.d nimbus defaults; 
	/etc/init.d/mysql start;
	/usr/bin/mysql -uroot -pn1mbus < /var/nimbus/create.sql 2> /dev/null || echo;

    /var/www/nimbus --create-database;
    chown -R www-data:www-data /etc/nimbus/;
    chown -R www-data:www-data /var/log/nimbus/;
    chown -R www-data:www-data /var/nimbus/;
    chown -R www-data:www-data /var/www/;
    chmod -R 0775 /var/log/nimbus/;
    chmod -R 0775 /var/nimbus/;
    chmod -R 0775 /etc/nimbus/;
    /etc/init.d/bacula-ctl-dir restart;
    /etc/init.d/bacula-ctl-sd restart;
    /etc/init.d/nimbus restart;
	/etc/init.d/nimbusmanager restart ;
    /etc/init.d/nginx restart;;
esac

